-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(C.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN AUTHOR AS A
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES AS C
ON C.BOOK_ID = B.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;