-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR,
        MONTH(B.SALES_DATE) AS MONTH,
        A.GENDER AS GENDER,
        COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO AS A
INNER JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
HAVING  GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;