WITH USER_INFO_NEW AS (
    SELECT * FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT O.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) FROM USER_INFO_NEW), 1) PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO_NEW N
ON O.USER_ID = N.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2;