SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) TOTAL_SALES FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY O.PRODUCT_ID
ORDER BY 3 DESC, 1;