SELECT 
    H.HISTORY_ID,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7
            THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30
            THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 
                (1 - (SELECT D.DISCOUNT_RATE 
                      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
                      WHERE D.CAR_TYPE = '트럭' AND D.DURATION_TYPE LIKE '7%') * 0.01))
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90
            THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 
                (1 - (SELECT D.DISCOUNT_RATE 
                      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
                      WHERE D.CAR_TYPE = '트럭' AND D.DURATION_TYPE LIKE '30%') * 0.01))
        ELSE 
            ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 
                (1 - (SELECT D.DISCOUNT_RATE 
                      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
                      WHERE D.CAR_TYPE = '트럭' AND D.DURATION_TYPE LIKE '90%') * 0.01))
    END AS FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN 
    CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    2 DESC, 1 DESC;