WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME
    WHERE HOUR < 23)

SELECT T.HOUR AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT JOIN TIME AS T 
ON HOUR(A.DATETIME) = T.HOUR
GROUP BY 1
ORDER BY 1;