-- 코드를 입력하세요
SELECT A.CAR_ID FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
WHERE B.START_DATE >= "2022-10-01" AND B.START_DATE <= "2022-10-31" AND A.CAR_TYPE = "세단"
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC;